### ISSUE TITLE
Please release a tarball for 5.0 or the latest version

### ISSUE THREAD

**Issue by hughmcmaster** [silnrsi/grcompiler#12]
The most recent source tarball available is 4.3.1, but the source indicates that grcompiler is at 5.0 or possibly even 5.1.

Please release a source tarball of the latest version available.

**Comment by bgermann** [comment]
Just tagging the versions would be awesome! If you do not have any hint which version is what git commit then nobody knows. Debian and Ubuntu therefore still provide version 4.2.

**Comment by sharoncorrell** [comment]
We will tag the source code as v. 5.1 once it is really finalized.

**Comment by bobh0303** [comment]
v5.2 tagged release available
