### ISSUE TITLE
Source files contain mixed line endings

### ISSUE THREAD

**Issue by hughmcmaster** [silnrsi/grcompiler#13]
The source files in the repository contain mixed line endings, e.g. LF or CR+LF.

While the Windows-specific files should use CR+LF, the other files should use LF.

This issue particularly affects test/GrcRegressionTest/configure.ac, which I am trying to patch using Debian Linux. Unfortunately, the patching process fails due to the line endings (it expects LF, not CR+LF).

Please at least convert test/GrcRegressionTest/configure.ac to LF (Linux/macOS) line endings.

Thank you

**Comment by sharoncorrell** [comment]
Done.
