### ISSUE TITLE
Regression test fails for a font with an explicit name specified

### ISSUE THREAD

**Issue by sharoncorrell** [silnrsi/grcompiler#17]
When a font is generated with an explicit name specified, the date the font was created is stored in certain fields in the name table (see BuildFontNames()). What this means is that the font won't match the benchmark IF it is generated on a different day.

This shows up in the regression tests with the "PigLatin GrRegTest V2" font.

**Comment by sharoncorrell** [comment]
On Bob's advice, I changed it to only include the year, not the full date. So now this test will only fail when run in a new year. In fact, it *should* fail if the font name is being regenerated correctly.

**Comment by bobh0303** [comment]
no further action needed
