### ISSUE TITLE
provide -o / --output parameter

### ISSUE THREAD

**Issue by n7s** [silnrsi/grcompiler#2]
When doing multiple chained runs of grcompiler (.i.e in a CI environment), the default output file for errors gdlerr.txt gets overwritten.  Can we please have an -o / --output parameter to name the output file? Smith (or other tools) can then use that parameter to write a file with the name of the font file in question.

**Comment by mhosken** [comment]
I would prefer -l / --log (for logging) rather than -o, since the output of grcompiler is a font, not a log file :)

**Comment by sharoncorrell** [comment]
I agree... -o is not appropriate. We already have an -offsets option. -l would be okay, or maybe -e for error file? To me "logging" sounds like something optional.

By the way, we are not right now supporting the letter and word versions of the options. We only support one form.

**Comment by bobh0303** [comment]
-l for "logfile", not for "logging"

**Comment by sharoncorrell** [comment]
I decided on -e for various reasons.

**Comment by sharoncorrell** [comment]
Implemented using -e.
