### ISSUE TITLE
CMake project generation failed on Win10 with VS 2019

### ISSUE THREAD

**Issue by nrsiward** [silnrsi/grcompiler#20]
After cloning the repo, I did the following from the grcompiler directory using the "Developer Command Prompt for VS 2019":
```
md build
cd build
cmake ..
```
which produced the following errors:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ICU_I18N_LIBRARY
    linked by target "grcompiler" in directory C:/Users/wardak/Mine/Src/GitHub/grcompiler/compiler
ICU_UC_LIBRARY
    linked by target "grcompiler" in directory C:/Users/wardak/Mine/Src/GitHub/grcompiler/compiler

-- Configuring incomplete, errors occurred!
```
I attached the CMake output log.
[CMakeOutput.log](https://github.com/silnrsi/grcompiler/files/3692664/CMakeOutput.log)

**Comment by nrsiward** [comment]
Do I need to some how install ICU? The readme.md file said

> The CMakeLists.txt will automatically fetch the icu4c.v140 nuget package for you and also a copy of nuget if it's not installed.

So, I thought installing ICU would be handled by CMake.

**Comment by nrsiward** [comment]
I did download `icu4c-65_1-Win64-MSVC2017.zip` from `site.icu-project.org` and set the `ICU_ROOT` environment variable to point to the extracted folder, but that didn't fix the CMake issue.

**Comment by tim-eves** [comment]
Unless it's changed for VS2019 you do need to set the `CMAKE_BUILD_TYPE` variable for Visual Studio support (see the README.md for an example). The nuget support in the scripts should download both nuget and the icu4c dependency automatically, but that maybe failing because of the incorrect `cmake ..` invocation.  The `ICU_ROOT` variable isn't an environment variable but a CMake variable, so you'd need to set with `-DICU_ROOT=`<path to built ICU files>. Assuming you've unzipped the zip file you mentioned into icu at the top of the grcompiler source tree, the following _should_ work:
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DICU_ROOT=..\icu
```
If it doesn't then I've got more debugging to do on Windows.

**Comment by nrsiward** [comment]
1. Using `cmake .. -DCMAKE_BUILD_TYPE=Release` did fix the project generation error and running `cmake --build .` worked; however, it seems to have built debug versions of the targets. For example, grcompiler.exe was built in the grcompiler\build\compiler\Debug folder along with the 'd' versions of the ICU dlls. (I tried specifying `-DCMAKE_BUILD_TYPE=Release` with the `cmake --build .` command but that seems illegal.)

2. FWIW, it is also using ICU 59 instead of a later version though I don't know if that matters much.

3. I also tried specifing `-DICU_ROOT` to see if it would build using the installed ICU instead of using nuget. This did not work, though I'm not sure if it was supposed to. Details are below.

Using `cmake .. -DCMAKE_BUILD_TYPE=Release -DICU_ROOT=%cd%\..\..\..\icu4c-65_1-Win64-MSVC2017` resulted in the following warning:

> Installed:
>     2 package(s) to packages.config projects
> CMake Warning (dev) at compiler/CMakeLists.txt:23 (find_package):
>   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   CMake variable ICU_ROOT is set to:
> 
>     C:\Users\wardak\Mine\Src\GitHub\grcompiler\build\..\..\..\icu4c-65_1-Win64-MSVC2017
> 
>   For compatibility, CMake is ignoring the variable.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found the following ICU libraries:
> --   uc (required)
> --   i18n (required)
> -- Found ICU: C:/Users/wardak/Mine/Src/icu4c-65_1-Win64-MSVC2017/include (found version "65.1")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/wardak/Mine/Src/GitHub/grcompiler/build

`cmake --build .` then failed with four unresolved external symbols:` _u_charDirection_65, _u_isMirrored_65, _u_charMirror_65,  _u_charType_65`

**Comment by nrsiward** [comment]
1. Using `cmake .. -DCMAKE_BUILD_TYPE=Release` did fix the project generation error and running `cmake --build .` worked. `cmake --build . --config release` also worked

2. FWIW, it is using ICU 59 instead of a later version though I don't know if that matters much.

3. I also tried specifying `-DICU_ROOT` to see if it would build using the installed ICU instead of using nuget. This did not work, though I'm not sure if it was supposed to. Details are below.

Using `cmake .. -DCMAKE_BUILD_TYPE=Release -DICU_ROOT=%cd%\..\..\..\icu4c-65_1-Win64-MSVC2017` resulted in the following warning:

> Installed:
>     2 package(s) to packages.config projects
> CMake Warning (dev) at compiler/CMakeLists.txt:23 (find_package):
>   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   CMake variable ICU_ROOT is set to:
> 
>     C:\Users\wardak\Mine\Src\GitHub\grcompiler\build\..\..\..\icu4c-65_1-Win64-MSVC2017
> 
>   For compatibility, CMake is ignoring the variable.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found the following ICU libraries:
> --   uc (required)
> --   i18n (required)
> -- Found ICU: C:/Users/wardak/Mine/Src/icu4c-65_1-Win64-MSVC2017/include (found version "65.1")
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/wardak/Mine/Src/GitHub/grcompiler/build

`cmake --build .` then failed with four unresolved external symbols:` _u_charDirection_65, _u_isMirrored_65, _u_charMirror_65,  _u_charType_65`

**Comment by tim-eves** [comment]
Either 59 or 65 are later than the previous versions of ICU used so I don't think it matters to grcompiler (it might matter to the regression test, as that has the capacity for icu version specific test cases). I'll need to dig into the ICU_ROOT override as we do want that working if grcompiler gets unicode names or other character metadata through that.

**Comment by tim-eves** [comment]
Looking again at your report it appears that it _did_ find both some libs and includes, but I suspect that it found the wrong version libs in the PATH, but the intended version of the headers, hence the missing symbols.  Could you either: 
- Attach your build/CMakeCache.txt file, that'll have the value for the actual found ICU libs.
- Re-run the cmake configure step on a fresh build dir but with -DICU_DEBUG=ON added to the command invocation.

**Comment by nrsiward** [comment]
Here's the build/CMakeCache.txt file
[CMakeCache.txt](https://github.com/silnrsi/grcompiler/files/3700539/CMakeCache.txt)

**Comment by nrsiward** [comment]
1. Using a 32-bit version of ICU eliminated the unresolved external symbol errors. However, the build still failed, which is why I was unsure if the build was 32- or 64-bit. We should probably clarify in the readme.md that a 32-bit build is used (though maybe that depends on which developer tools are active?).

2. Adding `cmake_policy(SET CMP0074 NEW)` to the CMakeLists.txt in the grcompiler directory eliminated the below warning during project generation:

> CMake Warning (dev) at compiler/CMakeLists.txt:23 (find_package):
> Policy CMP0074 is not set: find_package uses _ROOT variables.
> Run "cmake --help-policy CMP0074" for policy details. Use the cmake_policy
> command to set the policy and suppress this warning.

though this warning apparently does not cause any real problem. IOW, the build still works even with that warning once the below workaround is applied.

3. `cmake --build . --config Release` using a 32-bit ICU failed with this error:

> Error copying directory from "/Release" to "C:/Users/wardak/Mine/Src/GitHub/grcompiler/build/compiler/Release"

I don't know why it is trying to copy from `/Release` but **adding an empty directory by that name to my c: drive allowed the build to complete.** That's a very hacky workaround.

4. `grcompiler.exe` will not run and produce a usage message unless the correct ICU binaries specified by `-DICU_ROOT` are on the path or copied into the same folder as the .exe. (Note that the compiler may crash silently with no usage message and thus appear to be running if the dlls are not found.) 

On Linux this is probably handled by installing the compiler using CMake and on a user's Windows system by the Windows installer. It's unclear how to handle this for a developer's Windows system where an installer is not ran. Previously `nmake -f makefile.mak` copied the needed ICU dlls to the folder where grcompiler.exe was built. I don't how to handle this using a CMake-based project. I supposed the ICU bin directory could be added to the path, but that doesn't seem quite right if that folder is under the grcompiler directory. What if there is an older ICU installed on the system used by other installed software? Maybe there is no good way and developers just have to manage their systems actively.

Attached is the CMakeCache.txt file from a successful 32-bit build.
[CMakeCache.txt](https://github.com/silnrsi/grcompiler/files/3704253/CMakeCache.txt)
