### ISSUE TITLE
limited attributes in substitution passes

### ISSUE THREAD

**Issue by mhosken** [silnrsi/grcompiler#23]
The graphite engine has become stricter. The following are the only attributes that can be read or written to in a substitution pass:

- breakweight
- direction
- usern
- component.ref

All others will cause the font to be rejected.

So we need a compiler error if any other attributes than these are accessed in a subsitution pass.

**Comment by sharoncorrell** [comment]
Limiting the user slot attributes to the substitution pass will not work for Awami. There are several that are used in the positioning pass.

**Comment by sharoncorrell** [comment]
Never mind, I read the description wrong.

**Comment by sharoncorrell** [comment]
Is there a reason why `insert` is not allowed in the substitution pass?
The GDL doc says that the place to set justification attributes is in the substitution pass. Do we even support justification now?
(In theory you might want to sent `collision `and `sequence `attributes in the final substitution pass, but it seems like a stretch.)

**Comment by mhosken** [comment]
This is part of the transition towards enabling Graphite to be used as part of OpenType processing. As such, there are a few constraints that we have to take on:

- No attributes can get across the substitution/positioning transition
- No access to positioning attributes from substitution passes.

As you have discovered, yes things like `insert` are a pain and it would help if the compiler would give an error for such attributes. Here is what the Graphite engine accepts in the substitution passes now:

- breakweight
- direction
- user
- component references

There is no limit on positioning passes.

**Comment by sharoncorrell** [comment]
Actually, insert is most commonly used during attachments.
I disallowed justify, collision, sequence, and insert.
