### ISSUE TITLE
grcompiler 5.0.2 Does not work on windows 7 64-bit

### ISSUE THREAD

**Issue by Saeed854** [silnrsi/grcompiler#26]
Hello.
I have a problem with running **grcompiler v5.0.2**. when i want to use it, the program gives me this error:

**the program can't start because icuuc49.dll is missing from your computer. Try Reinstalling the program to fix this problem.**
Here is the image:
![grcompiler error 5.0.2](https://user-images.githubusercontent.com/65552918/82233653-9207cf80-9945-11ea-9d4e-7c49392b2648.jpg)
I am using Windows 64-bit.
the previous versions work good.

**Comment by bobh0303** [comment]
Hm, and the ICU49 download page at http://site.icu-project.org/download/49 seems to be broken.

**Comment by Saeed854** [comment]
I downloaded that file from somewhere. Now it gives the following error:
![bandicam 2020-05-18 21-58-29-119](https://user-images.githubusercontent.com/65552918/82242228-c03fdc00-9952-11ea-9733-aa75f37c1824.jpg)

**Comment by bobh0303** [comment]
I'm glad you found the missing dlls.   For your info, we should soon be releasing grcompiler 5.2, which comes with icu67 and thus Unicode 13 support.

**Comment by bobh0303** [comment]
v5.2 released on github
