### ISSUE TITLE
Include licenses in the Windows installer

### ISSUE THREAD

**Issue by bgermann** [silnrsi/grcompiler#30]
The Windows installer does not include any license information, only a hint in stddef.gdh. At least the third party licenses that you do not have the copyright for must be included. Just put them into the doc directory.
Additionally to the source's license directory, at least the ICU, LZ4, fcpp, and the Doulos font licenses must be included in any  distribution.

**Comment by nrsiward** [comment]
Licenses were added to the `license/LICENSING.txt` file.
