### ISSUE TITLE
Debian autoremoval next month

### ISSUE THREAD

**Issue by bgermann** [silnrsi/grcompiler#33]
You should have a look at #28, #31, #32 because they are going to be responsible for [removal of Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966168)'s (and after it, Ubuntu's) grcompiler package on Sep, 6th.

**Comment by devosb** [comment]
Thank you for pointing out the bugs. Am I correct that if the bugs are not fixed, then the 5.2 version of the package will not be in Debian (and therefore not in Ubuntu) but that the older 4.2 version will remain in both Debian (stable) and Ubuntu?

**Comment by bgermann** [comment]
4.2 will remain in stable (buster) but will be removed from testing and the next Ubuntu release. I guess it will remain in all released Ubuntu versions.
